TestCard.Web/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestCard.Web.Filters;
using TestCard.Web;
using TestCard.Properties.Resources;
using TestCard.Domain.Services;
using System.Net.Mime;
using TestCard.Web.Helpers;

namespace TestCard.Web.Controllers
{
    [AuthorizationFilter]
    public class CompanyController : BaseController
    {
        [PermissionFilter(TestCard.Domain.Permissions.View)]
        public ActionResult View(int? id)
        {
            return GetModel(id ?? -1);
        }

        [PermissionFilter(TestCard.Domain.Permissions.View)]
        public ActionResult List()
        {
            return View();
        }

        [PermissionFilter(TestCard.Domain.Permissions.Add)]
        public ActionResult Add()
        {
            var model = new Models.CompanyModel();

            return View(model);
        }

        [HttpPost]
        [PermissionFilter(TestCard.Domain.Permissions.Add)]
        public ActionResult Add(Models.CompanyModel model, HttpPostedFileWrapper logo, HttpPostedFileWrapper accrLogo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (FileHelper.IsNullOrOfType(logo, FileHelper.FileType.WebImage)
                        && FileHelper.IsNullOrOfType(accrLogo, FileHelper.FileType.WebImage))
                    {
                        using (var service = new CompanyService(CurrentUser))
                        {
                            var company = AutoMapper.Mapper.Map<Models.CompanyModel, TestCard.Domain.Company>(model);

                            service.SaveCompany(company, CurrentUser.PersonID, FileHelper.GetFileData(logo), FileHelper.GetFileData(accrLogo));

                            SetSuccessMessage();

                            //return RedirectToAction("Edit", new { @id = company.CompanyID });
                            return RedirectToAction("List");
                        }
                    }
                    else
                    {
                        SetErrorMessage(GeneralResource.ImageAllowedMessage);
                    }
                }
            }
            catch
            {
                SetErrorMessage();
            }

            return View(model);
        }

        [PermissionFilter(TestCard.Domain.Permissions.Edit)]
        public ActionResult Edit(int? id)
        {
            return GetModel(id ?? -1);
        }

        [HttpPost]
        [PermissionFilter(TestCard.Domain.Permissions.Edit)]
        public ActionResult Edit(int id, Models.CompanyModel model, HttpPostedFileWrapper logo, HttpPostedFileWrapper accrLogo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (FileHelper.IsNullOrOfType(logo, FileHelper.FileType.WebImage)
                        && FileHelper.IsNullOrOfType(accrLogo, FileHelper.FileType.WebImage))
                    {
                        using (var service = new CompanyService(CurrentUser))
                        {
                            var company = service.Get(id);

                            company = AutoMapper.Mapper.Map(model, company);

                            service.SaveCompany(company, CurrentUser.PersonID, FileHelper.GetFileData(logo), FileHelper.GetFileData(accrLogo));
                        }

                        SetSuccessMessage();
                        //return RedirectToAction("Edit", RouteData.Values);
                        return RedirectToAction("List");
                    }
                    else
                    {
                        SetErrorMessage(GeneralResource.ImageAllowedMessage);
                    }

                }
            }
            catch
            {
                SetErrorMessage();
            }


            return View(model);
        }

        private ActionResult GetModel(int id)
        {
            try
            {
                using (var service = new CompanyService(CurrentUser))
                {
                    var source = service.Get(id, true);

                    if (source != null)
                    {
                        var model = AutoMapper.Mapper.Map<Models.CompanyModel>(source);

                        return View(model);
                    }
                    else
                    {
                        SetErrorMessage(GeneralResource.RecordNotExists);
                    }
                }
            }
            catch
            {
                SetErrorMessage();
            }

            return RedirectToAction("List");
        }
    }
}

TestCard.Web/Controllers/PersonChangeRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestCard.Domain.Services;
using TestCard.Properties.Resources;
using TestCard.Web.Filters;
using TestCard.Web.Helpers;

namespace TestCard.Web.Controllers
{
    [AuthorizationFilter]
    public class PersonChangeRequestController : BaseController
    {
        public static object lockObject = new object();

        [PermissionFilter(TestCard.Domain.Permissions.View)]
        public ActionResult List()
        {
            return View();
        }

        [PermissionFilter(TestCard.Domain.Permissions.View)]
        public ActionResult View(int? id)
        {
            try
            {
                using (var service = new PersonChangeRequestService(CurrentUser))
                {
                    var source = service.Get(id ?? -1, true);

                    if (source != null)
                    {
                        var model = new Models.PersonModel();
                        model = AutoMapper.Mapper.Map(source, model);
                        //model.Schedule = new Models.PersonScheduleModel();
                        //model.Schedule.Days = AutoMapper.Mapper.Map<List<Models.PersonScheduleModel.Day>>(source.PersonScheduleChangeRequests.ToList());

                        ModelDataHelper.Populate(model);
                        //ModelDataHelper.PopulatePersonScheduleModel(model.Schedule);

                        return View(model);
                    }
                    else
                    {
                        SetErrorMessage(GeneralResource.RecordNotExists);
                    }
                }
            }
            catch
            {
                SetErrorMessage();
            }

            return RedirectToAction("List", "PersonChangeRequest");
        }

        [HttpPost]
        [PermissionFilter(TestCard.Domain.Permissions.Edit)]
        public ActionResult ProcessRequest(int id, Domain.ConfirmStatuses status)
        {
            try
            {
                lock (lockObject)
                {
                    using (var service = new PersonChangeRequestService())
                    {
                        bool? alreadyProcessed = null;
                        bool? notApprovedByQualityManager = null;

                        var saved = service.ChangeRequestStatus(id,
                            status,
                            CurrentUser.AccountType,
                            CurrentUser.PersonID,
                            ref alreadyProcessed,
                            ref notApprovedByQualityManager);

                        if (saved)
                        {
                            if (status == Domain.ConfirmStatuses.Approved)
                            {
                                SetSuccessMessage(GeneralResource.RequestApproved);
                            }
                            else
                            {
                                SetSuccessMessage(GeneralResource.RequestRejected);
                            }
                        }
                        else
                        {
                            if (alreadyProcessed == true)
                            {
                                SetErrorMessage(GeneralResource.RequestAlreadyProcessed);
                            }

                            if (notApprovedByQualityManager == true)
                            {
                                SetErrorMessage(GeneralResource.RequestNotApprovedByQualityManager);
                            }
                        }
                    }
                }
            }
            catch (Exception e)
            {
                SetErrorMessage();
            }

            return RedirectToAction("List", "PersonChangeRequest");
        }
    }
}

TestCard.Web/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestCard.Domain.Services;
using TestCard.Properties.Resources;
using TestCard.Web.Filters;
using TestCard.Web.Helpers;

namespace TestCard.Web.Controllers
{
    [AuthorizationFilter]
    public class PersonController : BaseController
    {
        [PermissionFilter(TestCard.Domain.Permissions.View)]
        public ActionResult List()
        {
            return View();
        }

        [PermissionFilter(TestCard.Domain.Permissions.View)]
        public ActionResult View(int? id)
        {
            return GetModel(id ?? -1);
        }

        [PermissionFilter(TestCard.Domain.Permissions.Add)]
        public ActionResult Add()
        {
            var model = new TestCard.Web.Models.RegisterModel();
            ModelDataHelper.Populate(model);

            return View(model);
        }

        [HttpPost]
        [PermissionFilter(TestCard.Domain.Permissions.Add)]
        public ActionResult Add(TestCard.Web.Models.RegisterModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var service = new PersonChangeRequestService())
                    {
                        var per = AutoMapper.Mapper.Map<Models.RegisterModel, TestCard.Domain.PersonChangeRequest>(model);

                        bool? hasUnconfirmedRequest = null;
                        var saved = service.SaveChangeRequest(per, CurrentUser, ref hasUnconfirmedRequest);

                        if (saved)
                        {
                            SetSuccessMessage();
                            if (CurrentUser.AccountType == Domain.AccountTypes.Administrator)
                            {
                                //return RedirectToAction("Edit", new { @id = per.PersonID });
                                return RedirectToAction("List");
                            }
                            else
                            {
                                return RedirectToAction("List", "PersonChangeRequest");
                            }
                        }
                        else if (hasUnconfirmedRequest == true)
                        {
                            SetErrorMessage(GeneralResource.UserHasUnconfirmedRequest);
                        }
                    }
                }
            }
            catch
            {
                SetErrorMessage();
            }

            ModelDataHelper.Populate(model);

            return View(model);
        }

        [PermissionFilter(TestCard.Domain.Permissions.Edit)]
        public ActionResult Edit(int? id)
        {
            return GetModel(id ?? -1);
        }

        [HttpPost]
        [PermissionFilter(TestCard.Domain.Permissions.Edit)]
        public ActionResult Edit(int id, Models.PersonModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var service = new PersonChangeRequestService())
                    {
                        var per = AutoMapper.Mapper.Map<Domain.PersonChangeRequest>(model);

                        bool? hasUnconfirmedRequest = null;
                        var saved = service.SaveChangeRequest(per, CurrentUser, ref hasUnconfirmedRequest);

                        if (saved)
                        {
                            SetSuccessMessage();

                            if (CurrentUser.AccountType == Domain.AccountTypes.Administrator)
                            {
                                //return RedirectToAction("Edit", RouteData.Values);
                                return RedirectToAction("List");
                            }
                            else
                            {
                                return RedirectToAction("List", "PersonChangeRequest");
                            }
                        }
                        else if (hasUnconfirmedRequest == true)
                        {
                            SetErrorMessage(GeneralResource.UserHasUnconfirmedRequest);
                        }
                    }
                }
            }
            catch
            {
                SetErrorMessage();
            }

            ModelDataHelper.Populate(model);

            return View(model);
        }

        public ActionResult GetModel(int id)
        {
            try
            {
                using (var service = new PersonService(CurrentUser))
                {
                    var source = service.Get(id, true);

                    if (source != null)
                    {
                        var model = new Models.PersonModel();
                        model = AutoMapper.Mapper.Map(source, model);
                        //model.Schedule = new Models.PersonScheduleModel();
                        //model.Schedule.Days = AutoMapper.Mapper.Map<List<Models.PersonScheduleModel.Day>>(source.PersonSchedules.ToList());

                        ModelDataHelper.Populate(model);
                        //ModelDataHelper.PopulatePersonScheduleModel(model.Schedule);

                        return View(model);
                    }
                    else
                    {
                        SetErrorMessage(GeneralResource.RecordNotExists);
                    }
                }
            }
            catch
            {
                SetErrorMessage();
            }

            return RedirectToAction("List");
        }
    }
}

TestCard.Web/Controllers/TestingCardChangeRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestCard.Domain.Services;
using TestCard.Properties.Resources;
using TestCard.Web.Filters;
using TestCard.Web.Helpers;

namespace TestCard.Web.Controllers
{
    [AuthorizationFilter]
    public class TestingCardChangeRequestController : BaseController
    {
        public static object lockObject = new object();

        [PermissionFilter(TestCard.Domain.Permissions.View)]
        public ActionResult List()
        {
            return View();
        }

        [PermissionFilter(TestCard.Domain.Permissions.View)]
        public ActionResult View(int? id)
        {
            try
            {
                using (var service = new TestingCardChangeRequestService(CurrentUser))
                {
                    var source = service.Get(id, true);

                    if (source != null)
                    {
                        var model = new Models.TestingCardChangeRequestModel();
                        model = AutoMapper.Mapper.Map(source, model);

                        ModelDataHelper.Populate(model);

                        return View(model);
                    }
                    else
                    {
                        SetErrorMessage(GeneralResource.RecordNotExists);
                    }
                }
            }
            catch
            {
                SetErrorMessage();
            }

            return RedirectToAction("List", "TestingCardChangeRequest");
        }

        [HttpPost]
        [PermissionFilter(TestCard.Domain.Permissions.Edit)]
        public ActionResult ProcessRequest(int id, Domain.ConfirmStatuses status)
        {
            try
            {
                lock (lockObject)
                {
                    using (var service = new TestingCardChangeRequestService())
                    {
                        bool? alreadyProcessed = null;
                        bool? notApprovedByQualityManager = null;

                        var saved = service.ChangeRequestStatus(id,
                            status,
                            CurrentUser.AccountType,
                            CurrentUser.PersonID,
                            ref alreadyProcessed,
                            ref notApprovedByQualityManager);

                        if (saved)
                        {
                            if (status == Domain.ConfirmStatuses.Approved)
                            {
                                SetSuccessMessage(GeneralResource.RequestApproved);
                            }
                            else
                            {
                                SetSuccessMessage(GeneralResource.RequestRejected);
                            }
                        }
                        else
                        {
                            if (alreadyProcessed == true)
                            {
                                SetErrorMessage(GeneralResource.RequestAlreadyProcessed);
                            }

                            if (notApprovedByQualityManager == true)
                            {
                                SetErrorMessage(GeneralResource.RequestNotApprovedByQualityManager);
                            }
                        }
                    }
                }
            }
            catch (Exception e)
            {
                SetErrorMessage();
            }

            return RedirectToAction("List", "TestingCardChangeRequest");
        }
    }
}

TestCard.Web/Views/List/Company.cshtml
@model IEnumerable<TestCard.Web.Models.CompanyListModel>
<div class="x-table-cont">
    <table class="x-table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccreditationScope)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccreditationNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccreditationExpireDate)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.CompanyName, "View", "Company", new { @id = item.CompanyID }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AccreditationScope)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AccreditationNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AccreditationExpireDate)
                </td>
                @{ Html.RenderPartial("_ActionCell", new ActionCell
               {
                   EntityObject = TestCard.Domain.Objects.Company,
                   Items = new List<ActionButton> {
                        new ActionButton
                        {
                            Controller = "Company",
                            ObjectID = item.CompanyID,
                            Type = ActionButton.ActionTypes.Edit
                        }
                    }
               }); }
            </tr>
        }
    </table>
</div>
@{Html.Pager((IPagedList)Model, "Company", "Company");}

TestCard.Web/Views/List/Person.cshtml
@model IEnumerable<TestCard.Web.Models.PersonListModel>
<div class="x-table-cont">
    <table class="x-table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IDNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccountTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IDNo)
                </td>
                <td>
                    @Html.ActionLink(item.FullName, "View", "Person", new { @id = item.PersonID }, null)
                </td>
                <td>
                    @Html.ActionLink(item.CompanyName, "View", "Company", new { @id = item.CompanyID }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AccountTypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mobile)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                @{ Html.RenderPartial("_ActionCell", new ActionCell
               {
                   EntityObject = TestCard.Domain.Objects.Person,
                   Items = new List<ActionButton> {
                        new ActionButton
                        {
                            Controller = "Person",
                            ObjectID = item.PersonID,
                            Type = ActionButton.ActionTypes.Edit
                        }
                   }
               }); }
            </tr>
        }
    </table>
</div>
@{Html.Pager((IPagedList)Model, "Person", "Person");}

TestCard.Web/Views/List/PersonStatistic.cshtml
@model IEnumerable<TestCard.Web.Models.PersonStatisticListModel>
<div class="x-table-cont">
    <table class="x-table">
        <thead>
            <tr>
                <th rowspan="2">
                    @Html.DisplayNameFor(item => item.PersonFullName)
                </th>
                <th rowspan="2">
                    @Html.DisplayNameFor(item => item.CompanyName)
                </th>
                <th rowspan="2">
                    @Html.DisplayNameFor(item => item.ScheduleChangeRequestCnt)
                </th>
                <th rowspan="2">
                    @Html.DisplayNameFor(item => item.FilledCardCnt)
                </th>
                <th rowspan="2">
                    @Html.DisplayNameFor(item => item.TestingCardChangeRequestCnt)
                </th>
                <th rowspan="2">
                    @Html.DisplayNameFor(item => item.TestingCardDailyAvg)
                </th>
                <th rowspan="2">
                    @Html.DisplayNameFor(item => item.UserOnlineTime)
                </th>
                <th colspan="2">@GeneralResource.CardCount</th>
                <th colspan="2">@GeneralResource.CardCount</th>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(item => item.ValidCardCnt)
                </th>
                <th>
                    @Html.DisplayNameFor(item => item.InvalidCardCnt)
                </th>
                <th>
                    @Html.DisplayNameFor(item => item.FirstTestingCnt)
                </th>
                <th>
                    @Html.DisplayNameFor(item => item.SecondaryTestingCnt)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.PersonFullName, "View", "Person", new { @id = item.PersonID }, null)
                    </td>
                    <td>
                        @Html.ActionLink(item.CompanyName, "View", "Company", new { @id = item.CompanyID }, null)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ScheduleChangeRequestCnt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FilledCardCnt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TestingCardChangeRequestCnt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TestingCardDailyAvg)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserOnlineTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ValidCardCnt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InvalidCardCnt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstTestingCnt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SecondaryTestingCnt)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@{Html.Pager((IPagedList)Model, "PersonStatistic", "PersonStatistic");}

TestCard.Web/Views/List/TestingCard.cshtml
@model IEnumerable<TestCard.Web.Models.TestingCardListModel>
<div class="x-left">
    @{ Html.RenderPartial("_ActionBar", new ActionBar
       {
           EntityObject = TestCard.Domain.Objects.TestingCard,
           Items = new List<ActionButton>
           {
               new ActionButton { 
                   Type = ActionButton.ActionTypes.Add, 
                   Text = GeneralResource.Add,
                   Url = Url.Action("Add", "TestingCard")
               }
           }
       }); 
    }
</div>
@{ Html.RenderPartial("_ListFilter", new AjaxListModel
   {
       ActionName = "TestingCard",
       Filter = ((IFilteredList)Model).Filter
   }); }
<div class="x-table-cont">
    <table class="x-table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TestingCardNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EffectiveDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RespPersonFullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarBrandAndModel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarSerialNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VIN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirnishNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirnishDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valid)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.TestingCardNumber, "View", "TestingCard", new { @id = item.TestingCardID }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EffectiveDate)
                </td>
                <td>
                    @Html.ActionLink(item.CompanyName, "View", "Company", new { @id = item.CompanyID }, null)
                </td>
                <td>
                    @Html.ActionLink(item.RespPersonFullName, "View", "Person", new { @id = item.ResponsiblePersonID }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CarBrandAndModel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CarNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CarSerialNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VIN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirnishNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirnishDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valid)
                </td>
                @{ Html.RenderPartial("_ActionCell", new ActionCell
               {
                   EntityObject = TestCard.Domain.Objects.TestingCard,
                   Items = new List<ActionButton> {
                        new ActionButton
                        {
                            Controller = "TestingCard",
                            ObjectID = item.TestingCardID,
                            Type = ActionButton.ActionTypes.Edit
                        },
                        new ActionButton
                        {
                            Controller = "Print",
                            Action = "TestingCard",
                            ObjectID = item.TestingCardID,
                            Type = ActionButton.ActionTypes.Print,
                            Target = "_blank"
                        }
                    }
               }); }

            </tr>
        }
    </table>
</div>
@{Html.Pager((IPagedList)Model, "TestingCard", "TestingCard");}